### ISSUE TITLE
fix broken `ogImage` link in blog posts

### ISSUE THREAD

**Issue by mabdullahadeel** [mabdullahadeel/abdadeel.com#4]

**Comment by siail** [comment]
the approach taken for the solution if not the best but works for now.

Since og images needs to be served as static, the blog image then needs to be duplicated in `public` and `src/assets` folder. All images in blog posts lives in `src/assets` since `astro` optimizes them when placed in that specific folder.

Thus for now, blog header image has to be placed in both `public` and `src/assets` and used in `.md` blog posts accordingly.
